apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  labels:
    #app.kubernetes.io/name: vote
    #app.kubernetes.io/part-of: vote
  #namespace: vote
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/add-base-url : "true"
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #cert-manager.io/cluster-issuer: "test-selfsigned"
    cert-manager.io/issuer: "test-selfsigned"
     #alias /;
  # location / {root /};
    # UPDATE THIS LINE ABOVE
spec:
  tls:
    - hosts:
      - ingress.example.com
      secretName: selfsigned-cert-tls
  rules:
    - host: ingress.example.com
      http:
        paths:
          # - path: /?(.*)
          - path: /
          # UPDATE THIS LINE ABOVE
            backend:
              serviceName: vote
              servicePort: 80
          - path: /static/stylesheets/style.css
          # UPDATE THIS LINE ABOVE
            backend:
              serviceName: vote
              servicePort: 80
          - path: /result
          # UPDATE THIS LINE AB?(.*)OVE
            backend:
              serviceName: result
              servicePort: 80
          - path: /results/?(.*)
          # UPDATE THIS LINE AB?(.*)OVE
            backend:
              serviceName: result
              servicePort: 80
          #- path: /stylesheets/?(.*)
          # UPDATE THIS LINE AB?(.*)OVE
          #  backend:
          #    serviceName: result
          #    servicePort: 80
